"""
KYC Microservice — API Router
POST /verify-identity
"""

import asyncio
from fastapi import APIRouter, File, Form, UploadFile, status
from fastapi.responses import JSONResponse

from app.api.schemas import VerifyIdentityResponse, ErrorResponse
from app.core.config import get_settings
from app.core.exceptions import KYCException, LivenessFailedError, raise_http
from app.core.logging import get_logger
from app.utils.face_utils import (
    validate_upload,
    decode_image,
    check_image_sharpness,
    extract_face_encoding,
    compare_faces,
    check_liveness,
)

router = APIRouter(prefix="/verify-identity", tags=["KYC"])
settings = get_settings()
logger = get_logger(__name__)


@router.post(
    "",
    response_model=VerifyIdentityResponse,
    status_code=status.HTTP_200_OK,
    responses={
        400: {"model": ErrorResponse, "description": "No face / multiple faces / low quality"},
        422: {"model": ErrorResponse, "description": "Invalid file type or size"},
        500: {"model": ErrorResponse, "description": "Internal server error"},
    },
    summary="Verify identity by comparing a selfie with an ID card photo.",
)
async def verify_identity(
    selfie: UploadFile = File(..., description="Live selfie of the user (JPEG/PNG, max 5 MB)."),
    id_card: UploadFile = File(..., description="Front of the user's ID card (JPEG/PNG, max 5 MB)."),
    liveness_token: str | None = Form(
        default=None,
        description=(
            "Opaque token generated by the frontend after the user completes "
            "a liveness challenge (blink / head-turn)."
        ),
    ),
) -> VerifyIdentityResponse:
    """
    **Identity verification pipeline:**

    1. Validate both uploads (size + extension).
    2. Decode images to RGB arrays and check sharpness.
    3. Extract exactly one face encoding from each image.
    4. Compare encodings and derive a confidence score.
    5. Validate the liveness token.
    6. Return structured result.

    All heavy CV work is dispatched to a thread pool so the async event
    loop stays unblocked.
    """

    logger.info(
        "Incoming verification — selfie=%s (%d B) id_card=%s (%d B)",
        selfie.filename,
        selfie.size or 0,
        id_card.filename,
        id_card.size or 0,
    )

    try:
        # ── 1. Read raw bytes (async I/O) ──────────────────────────────────
        selfie_bytes, id_bytes = await asyncio.gather(selfie.read(), id_card.read())

        # ── 2. File-level validation (fast, synchronous) ───────────────────
        validate_upload(selfie_bytes, selfie.filename or "selfie.jpg", "selfie")
        validate_upload(id_bytes, id_card.filename or "id_card.jpg", "id_card")

        # ── 3. Decode & quality check (CPU — run in thread pool) ───────────
        loop = asyncio.get_event_loop()

        selfie_img = await loop.run_in_executor(
            None, decode_image, selfie_bytes, "selfie"
        )
        id_img = await loop.run_in_executor(
            None, decode_image, id_bytes, "id_card"
        )

        await loop.run_in_executor(None, check_image_sharpness, selfie_img, "selfie")
        await loop.run_in_executor(None, check_image_sharpness, id_img, "id_card")

        # ── 4. Face encoding (most CPU-intensive — thread pool) ────────────
        selfie_encoding, id_encoding = await asyncio.gather(
            loop.run_in_executor(None, extract_face_encoding, selfie_img, "selfie"),
            loop.run_in_executor(None, extract_face_encoding, id_img, "id_card"),
        )

        # ── 5. Face comparison ─────────────────────────────────────────────
        comparison = await loop.run_in_executor(
            None, compare_faces, selfie_encoding, id_encoding
        )
        logger.info(
            "Comparison result — match=%s confidence=%.2f%% distance=%.4f",
            comparison["match"],
            comparison["confidence"],
            comparison["distance"],
        )

        # ── 6. Liveness ────────────────────────────────────────────────────
        liveness_ok = check_liveness(liveness_token)
        if not liveness_ok:
            raise LivenessFailedError()

        # ── 7. Build response ──────────────────────────────────────────────
        verified = comparison["match"] and liveness_ok
        return VerifyIdentityResponse(
            match=comparison["match"],
            confidence=comparison["confidence"],
            message="verified" if verified else "not verified",
            liveness=liveness_ok,
            face_distance=comparison["distance"],
        )

    except KYCException as exc:
        logger.warning("KYC check failed: %s", exc.message)
        raise_http(exc)  # converts to HTTPException

    except Exception as exc:
        logger.exception("Unexpected error during identity verification: %s", exc)
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": "An internal error occurred. Please try again later."},
        )
